# Used when a release is pushed to GitHub
# This does not make use of any caching as to ensure a clean build
name: build-release

on:
  release:
     types:
       - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build artifacts
        run: ./gradlew build publishMods -Pbuild.release=true
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v2.0
        with:
          # Filter built files to disregard -sources and -dev, and leave only the minecraft-compatible jars.
          files: 'build/libs/*[0-9].jar;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
